// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psgcqyfwudgpbmthsfkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzZ2NxeWZ3dWRncGJtdGhzZmtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NDg1NTksImV4cCI6MjA2MjAyNDU1OX0.cwbZkAy8B6DTwwk_GhPKjRG6dPfwN6tpTmeGQvm3Rzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);